[package]
name = "restcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1" }
tokio = { version = "1.40.0", features = ["full"] }
mio = "^1.0.1"
